### ISSUE TITLE
Update url to www.projectfreetv.ws

### ISSUE THREAD

**Issue by supergibbs** [daattali/pftv-ad-bypass-extension#1]
Url changed (yet again) to http://www.projectfreetv.ws/

**Comment by daattali** [comment]
Thanks for the report, but I'm using http://projectfreetv.so/ and the website + extension still work for me. Let me know if `.so` doesn't work for you

**Comment by supergibbs** [comment]
Hmm, it's working for me now too. It wasn't earlier and found the other one. Maybe support both? Though the other could be a rip off...

**Comment by daattali** [comment]
I just looked into it a bit, but the logic would have to be different on the two sites. If `.so` does go down or another version becomes clearly better, I'll add support for it, but for now I don't see a reason to work on it since .so works just fine. Maybe the site was just down for a bit.  I'm closing the issue, feel free to re-open if it comes up again in the future!
